# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# 
# 

import sys
import itertools
from time import time

'''
Notes:


'''

def main(argv):
    first = 1
    second = 2
    new = first + second
    sum_of_evens = 2
    while ( new < 4000000 ):
        first = second
        second = new
        new = first + second
        print "first = " + str(first) + " second = " + str(second)
        if (second%2) == 0:
            # print "Adding second " + str(second)
            sum_of_evens += second
    print "SUM OF EVENS = " + str(sum_of_evens)

if __name__ == "__main__":
    main(sys.argv)
